volumes:
  wood_house_local_postgres_data: {}
  wood_house_local_postgres_data_backups: {}
  wood_house_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: wood_house_local_django
    container_name: wood_house_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8080:8000'  # Mengubah host port ke 8080
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: wood_house_production_postgres
    container_name: wood_house_local_postgres
    volumes:
      - wood_house_local_postgres_data:/var/lib/postgresql/data
      - wood_house_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: wood_house_local_mailpit
    ports:
      - "8125:8025"  # Mengubah host port ke 8125

  redis:
    image: docker.io/redis:6
    container_name: wood_house_local_redis
    volumes:
      - wood_house_local_redis_data:/data

  celeryworker:
    <<: *django
    image: wood_house_local_celeryworker
    container_name: wood_house_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: wood_house_local_celerybeat
    container_name: wood_house_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: wood_house_local_flower
    container_name: wood_house_local_flower
    ports:
      - '6666:5555'  # Mengubah host port ke 6666
    command: /start-flower
